FROM golang:1.24-alpine3.21

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download

# Install mysql-client which includes mysqldump
# The --no-cache option reduces image size by not storing package indexes
# The rm -rf /var/cache/apk/* cleans up the apk cache after installation
RUN apk add --no-cache mysql-client && \
    rm -rf /var/cache/apk/*

# COPY . .
# RUN go build -v -o /usr/local/bin/app ./...
#
# CMD ["app"]
