name: Docker Image Build

on:
  push:
    branches:
      - main # Or whatever branch you want to monitor (e.g., master, develop)

jobs:
  build:
    runs-on: ubuntu-latest
    # This condition checks if the commit message contains "docker build" (case-insensitive)
    if: contains(github.event.head_commit.message, 'docker build')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ github.sha }}
